version: '3.8'
services:

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
      POSTGRES_USER: "${DB_USERNAME:-user}"
      POSTGRES_DB: "${DB_DATABASE:-db}"
    ports:
      - "7432:5432"
    networks:
      - net


  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONTAINER_ROLE: "queue"
      RABBITMQ_HOST: "rabbitmq"
      DB_CONNECTION: "pgsql"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "${DB_DATABASE:-db}"
      DB_USERNAME: "${DB_USERNAME:-user}"
      DB_PASSWORD: "${DB_PASSWORD:-password}"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - net


  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq:/var/lib/rabbitmq"
    networks:
      - net

volumes:
  postgres_data:
  rabbitmq:
networks:
  net:

